# Generated by Django 5.1 on 2024-09-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_into_to_cards'),
        ('wallet', '0002_id_to_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='organisations',
        ),
        migrations.AddField(
            model_name='wallet',
            name='cards',
            field=models.ManyToManyField(related_name='wallets', to='card.card'),
        ),
    ]
