# Generated by Django 5.1 on 2024-09-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_cardshare_init'),
        ('wallet', '0003_wallet_card_for_orgaqnisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='cards',
            field=models.ManyToManyField(blank=True, null=True, related_name='wallets', to='card.card'),
        ),
    ]
