# Generated by Django 5.1 on 2024-09-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_into_to_cards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardShare',
        ),
    ]
