# Generated by Django 5.1 on 2024-09-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_cardshare_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
