# Generated by Django 5.1 on 2024-09-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation.model', '0004_organisationListMIX'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation.modellist',
            name='organisation.model',
            field=models.ManyToManyField(blank=True, related_name='organisation.model_links', to='organisation.model.organisation'),
        ),
    ]
