# Generated by Django 5.1 on 2024-09-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_organisationListMIX'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationslist',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='organisations_links', to='organisations.organisation'),
        ),
    ]
