# Generated by Django 5.1 on 2024-09-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_alter_organisationslist_organisations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganisationsList',
        ),
    ]
