# Generated by Django 5.1 on 2024-09-14 18:26

import organisations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_delete_organisationslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='pp',
            field=models.ImageField(blank=True, null=True, upload_to=organisations.models.organisation_pp_upload_to),
        ),
    ]
