start:
	@echo "Starting back :8000 and front :3000"

back:
	@echo "Starting back end"
	@cd back_end/root && python3 manage.py runserver

frontv1:
	@echo "Starting fron end"
	@cd frontEnd/v1 && npm run dev

frontv2:
	@echo "Starting fron end"
	@cd frontEnd/v2 && npm run dev

frontv3:
	@echo "Starting fron end"
	@cd frontEnd/v3 && npm run dev

frontv4:
	@echo "Starting fron end"
	@cd frontEnd/v4 && npm run dev

